### ISSUE TITLE
Problem with margins in css

### ISSUE THREAD

**Issue by kieffer-reitenbach** [kieffer-reitenbach/modularity-mindfulness#1]
There seems to be some issue with margins on the "section" part of my css, I don't have any margins or padding on them but they have so much white space around them in markbot. Any way to fix that?

I also can't seem to figure out why the "nav" is pushed slightly to the right?

@wendywarren
@anna-pokhilenko

**Comment by wendywarren** [comment]
Hi @kieffer-reitenbach!

I took a look and hopefully this helps. For the nav, it looks as though the padding on the ul hasn't been removed. UL's have a default padding on the left. That is what is causing it to be pushed slightly to the right. Set that to 0 and you should be good.

<img width="1425" alt="Screen Shot 2021-09-27 at 10 02 36 AM" src="https://user-images.githubusercontent.com/12865609/134924433-b40ca71f-573f-420f-a7c2-371cf4510912.png">

As for extra space around the section, it's coming from the figure element as you can see below. Normally you would set it to 0 but in this case we want to remove figure all together. 

<img width="1421" alt="Screen Shot 2021-09-27 at 10 02 58 AM" src="https://user-images.githubusercontent.com/12865609/134924987-b8bb6df5-e4f1-4150-8938-59b801ac1c46.png">

Since the content is more than just an image and caption, we can simply use the article as a container with the content (img, h2, p and link) nested inside.  

Don't hesitate to message me if you have any further questions.

Thanks,
Wendy
